W0628 06:16:46.702000 2669924 site-packages/torch/distributed/run.py:766] 
W0628 06:16:46.702000 2669924 site-packages/torch/distributed/run.py:766] *****************************************
W0628 06:16:46.702000 2669924 site-packages/torch/distributed/run.py:766] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0628 06:16:46.702000 2669924 site-packages/torch/distributed/run.py:766] *****************************************
**********Test Starting************
**********Test Starting************
**********Test Starting************
**********Test Starting************
  0%|          | 0/469 [00:00<?, ?it/s]  0%|          | 0/469 [00:00<?, ?it/s]  0%|          | 0/469 [00:00<?, ?it/s]  0%|          | 0/469 [00:00<?, ?it/s]PSNR is: 18.493724822998047
  0%|          | 0/469 [00:01<?, ?it/s]
PSNR is: 19.44837188720703
  0%|          | 0/469 [00:02<?, ?it/s]
PSNR is: 18.18121910095215
  0%|          | 0/469 [00:02<?, ?it/s]
PSNR is: 17.824691772460938
  0%|          | 0/469 [00:01<?, ?it/s]
[rank1]: Traceback (most recent call last):
[rank1]:   File "/scratch/mt/new-structure/experiments/msaeed/masters/SCA/MNIST/test-lca2.py", line 219, in <module>
[rank1]:     psnr_lst, ssim_lst, fid_lst=attack_test(train_loader, target_model, attack_model)
[rank1]:                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/scratch/mt/new-structure/experiments/msaeed/masters/SCA/MNIST/test-lca2.py", line 159, in attack_test
[rank1]:     print("SSIM is:", ssim_val)
[rank1]:                       ^^^^^^^^
[rank1]: UnboundLocalError: cannot access local variable 'ssim_val' where it is not associated with a value
[rank0]: Traceback (most recent call last):
[rank0]:   File "/scratch/mt/new-structure/experiments/msaeed/masters/SCA/MNIST/test-lca2.py", line 219, in <module>
[rank0]:     psnr_lst, ssim_lst, fid_lst=attack_test(train_loader, target_model, attack_model)
[rank0]:                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/scratch/mt/new-structure/experiments/msaeed/masters/SCA/MNIST/test-lca2.py", line 159, in attack_test
[rank0]:     print("SSIM is:", ssim_val)
[rank0]:                       ^^^^^^^^
[rank0]: UnboundLocalError: cannot access local variable 'ssim_val' where it is not associated with a value
[rank3]: Traceback (most recent call last):
[rank3]:   File "/scratch/mt/new-structure/experiments/msaeed/masters/SCA/MNIST/test-lca2.py", line 219, in <module>
[rank3]:     psnr_lst, ssim_lst, fid_lst=attack_test(train_loader, target_model, attack_model)
[rank3]:                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/scratch/mt/new-structure/experiments/msaeed/masters/SCA/MNIST/test-lca2.py", line 159, in attack_test
[rank3]:     print("SSIM is:", ssim_val)
[rank3]:                       ^^^^^^^^
[rank3]: UnboundLocalError: cannot access local variable 'ssim_val' where it is not associated with a value
[rank2]: Traceback (most recent call last):
[rank2]:   File "/scratch/mt/new-structure/experiments/msaeed/masters/SCA/MNIST/test-lca2.py", line 219, in <module>
[rank2]:     psnr_lst, ssim_lst, fid_lst=attack_test(train_loader, target_model, attack_model)
[rank2]:                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/scratch/mt/new-structure/experiments/msaeed/masters/SCA/MNIST/test-lca2.py", line 159, in attack_test
[rank2]:     print("SSIM is:", ssim_val)
[rank2]:                       ^^^^^^^^
[rank2]: UnboundLocalError: cannot access local variable 'ssim_val' where it is not associated with a value
[rank0]:[W628 06:17:21.453288801 ProcessGroupNCCL.cpp:1479] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
W0628 06:17:24.539000 2669924 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 2669929 closing signal SIGTERM
W0628 06:17:24.540000 2669924 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 2669930 closing signal SIGTERM
W0628 06:17:24.540000 2669924 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 2669931 closing signal SIGTERM
E0628 06:17:24.741000 2669924 site-packages/torch/distributed/elastic/multiprocessing/api.py:874] failed (exitcode: 1) local_rank: 0 (pid: 2669928) of binary: /home/m.saeed/miniconda3/envs/sca/bin/python3.12
Traceback (most recent call last):
  File "/home/m.saeed/miniconda3/envs/sca/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/m.saeed/miniconda3/envs/sca/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/m.saeed/miniconda3/envs/sca/lib/python3.12/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/home/m.saeed/miniconda3/envs/sca/lib/python3.12/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/home/m.saeed/miniconda3/envs/sca/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m.saeed/miniconda3/envs/sca/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 270, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
MNIST/test-lca2.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-06-28_06:17:24
  host      : gpunode01.imhotep.aic.gov.eg
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2669928)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
